### ISSUE TITLE
Customizer: Edit icons covered by background image

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#118]
Hey Ari

I happen to come across this issue:

<img width="1308" alt="Screen Shot 2019-10-27 at 12 27 04" src="https://user-images.githubusercontent.com/5323259/67637871-27157f00-f8b5-11e9-96be-24c60731210f.png">

Adjust the header padding and notice how it effects the edit icons.
The above example is set at padding: 0 0 0 10px.
I am also seeing it says invalid value.

Btw should there be two checkboxes? One for site title and another for tagline?

**Comment by aristath** [comment]
The edit-icons are a bit weird when combined with a css-grid.
Known issue, I just haven't found a fix for that one yet... The way WP positions them prevents them from overflowing their container.

>  I am also seeing it says invalid value.

Yeah, that will have to be fixed in Kirki. The problem there is the multiple values, it only checks for single value. I'll have to tweak the checks a bit to get this right.
I'll work on it now and include a fix in the theme 👍 

> Btw should there be two checkboxes? One for site title and another for tagline?

There _should_, yes. But that one is from WP-Core. I'll look for a way to override it, but WordPress's default behavior is to hide/show both.

**Comment by aristath** [comment]
Multiple-values issue fixed

**Comment by paaljoachim** [comment]
Btw I added a new issue for splitting site title and the tagline.
So that we can close this issue.
