### ISSUE TITLE
PHP warning when viewing some post formats

### ISSUE THREAD

**Issue by carolinan** [wplemon/gridd#62]
When I view the following posts of the [Theme Unit Test](https://github.com/WPTRT/theme-unit-test),
Post Format: Quote,
Post Format: Link,
Post Format: Status,
Post Format: Aside

I see the following warning:
```
Warning: Use of undefined constant key - assumed 'key' 
(this will throw an Error in a future version of PHP) 
in gridd/inc/classes/Blog.php on line 208
```

Gridd version 1.1.10
PHP version 7.2.15
WordPress Version 5.2.2

Related; these formats could use some white space above the content because without 
the post meta, the content may be too short and the size of the header is increased instead.

**Comment by aristath** [comment]
Thank you!
I don't know how this was missed before... it was a typo (`key` instead of `$key`).
Fix in the develop branch, will be included in the next version released later today :+1: 

> Related; these formats could use some white space above the content because without
the post meta, the content may be too short and the size of the header is increased instead.

That will depend on the theme-options...
In the Customizer > Theme Options > Grid, right next to the header users can define the height of the row. If they leave all rows to `auto` they will get resized to fit the content. If users want to lock the header to be a fix height they can change that value to whatever they want (see red circle in the screenshot below) :smiley: 
![image823](https://user-images.githubusercontent.com/588688/62005361-c0a88580-b13a-11e9-90aa-05915cac294b.png)
