### ISSUE TITLE
Bug: customizer -> Theme Options -> Footer -> Adjusting copyright area

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#71]
Hey

It suddenly happened.... no idea why.
I have tested this on two dev sites.

customizer -> Theme Options -> Footer -> Adjusting copyright area

<img width="286" alt="Screen Shot 2019-07-29 at 14 32 24" src="https://user-images.githubusercontent.com/5323259/62048693-d63aaf80-b20d-11e9-9127-faf6cd10f1a9.png">

Click the customize Copyright Area.

![Copyright-section-Gridd-theme](https://user-images.githubusercontent.com/5323259/62048806-0c782f00-b20e-11e9-90dc-b39c6bbef6a3.gif)

**Comment by aristath** [comment]
Took me a while to find this...
Issue only occurs when Gutenberg is activated as a plugin.
The reason is the experiments Gutenberg is doing with blocks in widgets. They are causing a conflict with TinyMCE which just crashes everything.
I pushed a fix in the dev branch, this will be included in v1.1.12 which will be released in a few hours.
