### ISSUE TITLE
Aligning two widgets next to each other

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#82]
Hey

I am creating a top bar/preheader above the header.

Here is the Header grid with two widgets beside each other.
![Screen Shot 2019-08-07 at 13 58 11](https://user-images.githubusercontent.com/5323259/62621155-7f269000-b91b-11e9-9b5e-1286dd899c04.png)

With a height of 55 px.

Widget 1.
Added padding along the left area.
![Screen Shot 2019-08-07 at 13 59 56](https://user-images.githubusercontent.com/5323259/62621240-b432e280-b91b-11e9-8f3d-d2f190324b1f.png)

Widget 2.
Added padding along the right area.
![Screen Shot 2019-08-07 at 14 01 17](https://user-images.githubusercontent.com/5323259/62621337-e93f3500-b91b-11e9-8885-1a2b00477190.png)

Then added this CSS:
.gridd-tp-sidebar_2 {
    text-align: right !important;
}

As it moves widget 2 to the right.

Result:

![Screen Shot 2019-08-07 at 14 03 34](https://user-images.githubusercontent.com/5323259/62621465-2d323a00-b91c-11e9-98f2-237b087287ec.png)

It would make for a good doc example on how to add a preheader/topbar area.
I need to figure out a good way to stretch out th menu so that it does not lump up on the right....

**Comment by aristath** [comment]
You could also create a new columns element in Gutenberg, add your left-aligned content on the left column, your right-aligned content on the right column, then save the columns block as a reusable block. Give it a name, and then you can just use that in your grid since reusable blocks can be placed wherever you want them to be - including the header.
With blocks coming to widgets pretty soon (I think the Gutenberg plugin already adds them experimentally) I don't think we'll need docs for things like that...
