### ISSUE TITLE
Adding background image affects readability of site

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#98]
I added a background image..

![Screen Shot 2019-08-30 at 13 30 41](https://user-images.githubusercontent.com/5323259/64017631-62e8ce00-cb2a-11e9-8d4a-331787b10446.png)

Backend Gutenberg the link is white on white:

![Screen Shot 2019-08-30 at 13 31 11](https://user-images.githubusercontent.com/5323259/64017664-7c8a1580-cb2a-11e9-941d-a2fd231ee7d1.png)

**Comment by aristath** [comment]
Of course it is.
So you added a page background, and then in the content area you made he background color completely transparent?

**Comment by paaljoachim** [comment]
I added the page background and changed opacity on various background colors and the Gutenberg background made the link transparent just like is seen in the above screenshot.

**Comment by aristath** [comment]
I don't think that's exactly an "issue"...
Gutenberg does not offer a preview of the site. It is a preview of the content area. As such, the theme only adds styles to the editor that are related to the content itself.
I can't add the background image there because the backround image relates to the _site_, not the _content_. The fact that you used a full-transparent background-color for the content is really an edge-case, not the norm.
What I *can* do however, is add a switch that will allow users to completely disable gridd's editor styles if they wish.

**Comment by aristath** [comment]
Option will be added in v1.1.18 (will be released later today hopefully or tomorrow).
Once the update is released you'll be able to find the option in Customizer > Theme Options > Theme Features > Disable Editor Styles.
